/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:471828fb-97d8-4d48-8cbc-2eea5d84790c",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_NUPOZ3Kjq",
    "aws_user_pools_web_client_id": "2g0ic8ll1ir0jjus2dh9k3s4j8",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xgwcste6snekbppz4w7gag6pz4.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "nyxo-cloud-preprod-production",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "https://drjqoppqqmncl.cloudfront.net"
};


export default awsmobile;
